# Generated by Django 4.2.29 on 2026-03-06 01:26

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0012_orgregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='https://r-ai.business-pad.com/api/ai_request/', help_text='Адрес LLM API, например https://r-ai.business-pad.com/api/ai_request/', verbose_name='URL API')),
                ('auth_header', models.CharField(blank=True, default='Basic YXBpX3VzZXI6QXBpVXNlclRlc3QxMjMh', help_text='Значение заголовка Authorization (Basic / Bearer …)', max_length=512, verbose_name='Authorization')),
                ('referer', models.CharField(blank=True, default='https://core.business-pad.com/', help_text='Значение заголовка Referer', max_length=256, verbose_name='Referer')),
                ('request_template', models.TextField(default='{\n  "question_to_send": "{prompt}",\n  "session_id": "{session_id}",\n  "user": "openai",\n  "log_id": "{log_id}"\n}', help_text='JSON-шаблон запроса к API. Доступные плейсхолдеры: {prompt} — текст запроса, {session_id} — идентификатор сессии, {log_id} — идентификатор лога.', verbose_name='Шаблон тела запроса (JSON)')),
                ('response_key', models.CharField(blank=True, default='messages', help_text='Ключ верхнего уровня в ответе API. Если значение — список, берётся последний элемент. Запасной ключ: "response".', max_length=128, verbose_name='Ключ ответа в JSON')),
            ],
            options={
                'verbose_name': 'Настройки LLM API',
                'verbose_name_plural': 'Настройки LLM API',
            },
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='recordings.recording'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='transcribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Транскбировано'),
        ),
        migrations.AlterField(
            model_name='recordingembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='sharetoken',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='recordings.recording'),
        ),
    ]
