# Generated by Django 4.2.29 on 2026-03-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0026_meetingroom_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='transcription_stage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Этап транскрибации'),
        ),
    ]
