# Generated by Django 4.2.29 on 2026-03-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0031_botchathistory_ocr_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchathistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
