# Generated by Django 4.2.29 on 2026-03-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0044_siteuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
