# Generated by Django 4.2.29 on 2026-03-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0053_meetingroom_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micropreset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
