# Generated by Django 4.2.29 on 2026-03-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_kb', '0005_wikiarticlechunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikiarticleembedding',
            options={'verbose_name': 'Эмбеддинг статьи (устар.)', 'verbose_name_plural': 'Эмбеддинги статей (устар.)'},
        ),
    ]
