# Generated by Django 5.2.8 on 2025-11-22 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('signature', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подпись')),
                ('transcribed_text', models.TextField(verbose_name='Транскрибированный текст')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байты)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Транскрипция',
                'verbose_name_plural': 'Транскрипции',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
