# Generated by Django 5.2.8 on 2025-11-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='password_phrase_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хеш фразы-пароля'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['password_phrase_hash'], name='transcribe__passwor_b68d54_idx'),
        ),
    ]
