# Generated by Django 5.2.8 on 2025-11-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0002_transcription_password_phrase_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='extract_screenshots',
            field=models.BooleanField(default=False, verbose_name='Извлечь скриншоты'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(verbose_name='Временная метка (секунды)')),
                ('image_path', models.CharField(max_length=500, verbose_name='Путь к изображению')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='transcribe.transcription', verbose_name='Транскрипция')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
                'ordering': ['order', 'timestamp'],
            },
        ),
    ]
