# Generated by Django 5.2.8 on 2025-11-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0003_transcription_extract_screenshots_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='upload_session',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сессия загрузки'),
        ),
    ]
