# Generated by Django 5.2.8 on 2025-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0004_transcription_upload_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='public_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Публичный токен для доступа'),
        ),
    ]
