# Generated by Django 5.2.8 on 2025-11-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0005_transcription_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='whisper_model',
            field=models.CharField(choices=[('tiny', 'Tiny (быстрая, низкое качество)'), ('base', 'Base (баланс, по умолчанию)'), ('small', 'Small (хорошее качество)'), ('medium', 'Medium (высокое качество)'), ('large-v2', 'Large-v2 (лучшее качество, медленно)'), ('large-v3', 'Large-v3 (лучшее качество, медленно)')], default='base', max_length=20, verbose_name='Модель Whisper'),
        ),
    ]
