# Generated by Django 5.2.8

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0006_transcription_whisper_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPUploadCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP адрес')),
                ('upload_count', models.IntegerField(default=0, verbose_name='Количество загрузок')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('last_upload_at', models.DateTimeField(auto_now=True, verbose_name='Последняя загрузка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Счетчик загрузок по IP',
                'verbose_name_plural': 'Счетчики загрузок по IP',
                'ordering': ['-last_upload_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ipuploadcount',
            index=models.Index(fields=['ip_address'], name='transcribe_i_ip_addr_idx'),
        ),
    ]

