# Generated by Django 5.2.8

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0007_ipuploadcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID пользователя'),
        ),
        migrations.CreateModel(
            name='UUIDUploadCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID пользователя')),
                ('upload_count', models.IntegerField(default=0, verbose_name='Количество загрузок')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('last_upload_at', models.DateTimeField(auto_now=True, verbose_name='Последняя загрузка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Счетчик загрузок по UUID',
                'verbose_name_plural': 'Счетчики загрузок по UUID',
                'ordering': ['-last_upload_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uuiduploadcount',
            index=models.Index(fields=['uuid'], name='transcribe_u_uuid_idx'),
        ),
    ]

