# Generated by Django 5.2.8 on 2025-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0008_transcription_user_uuid_uuiduploadcount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ipuploadcount',
            new_name='transcribe__ip_addr_958143_idx',
            old_name='transcribe_i_ip_addr_idx',
        ),
        migrations.RenameIndex(
            model_name='uuiduploadcount',
            new_name='transcribe__uuid_6534c2_idx',
            old_name='transcribe_u_uuid_idx',
        ),
        migrations.AddField(
            model_name='transcription',
            name='transcription_logs',
            field=models.TextField(blank=True, null=True, verbose_name='Логи транскрибации'),
        ),
    ]
