# Generated by Django 5.2.8 on 2025-11-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0009_add_transcription_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='original_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к оригинальному файлу'),
        ),
    ]
