# Generated by Django 5.2.8 on 2025-11-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0009_transcription_detected_language_language_confirmed'),
        ('transcribe', '0010_add_original_file_path'),
    ]

    operations = [
    ]
