# Generated by Django 5.2.8 on 2025-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0011_merge_20251125_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipuploadcount',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='uuiduploadcount',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
