# Generated by Django 5.2.8 on 2025-11-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0012_ipuploadcount_balance_uuiduploadcount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='selected_language',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Выбранный язык'),
        ),
    ]
