# Generated by Django 5.2.8 on 2025-12-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0013_transcription_selected_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='screenshot_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Извлекаем слайды'), ('completed', 'Слайды готовы'), ('skipped', 'Пропущено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус извлечения скриншотов'),
        ),
    ]
